// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscountService.proto

package com.github.joaolucasl.chumlee;

public final class DiscountServiceOuterClass {
  private DiscountServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DiscountRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.joaolucasl.chumlee.DiscountRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string product_id = 2;</code>
     */
    java.lang.String getProductId();
    /**
     * <code>string product_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductIdBytes();
  }
  /**
   * Protobuf type {@code com.github.joaolucasl.chumlee.DiscountRequest}
   */
  public  static final class DiscountRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.joaolucasl.chumlee.DiscountRequest)
      DiscountRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DiscountRequest.newBuilder() to construct.
    private DiscountRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DiscountRequest() {
      userId_ = "";
      productId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DiscountRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              productId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest.class, com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string user_id = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object productId_;
    /**
     * <code>string product_id = 2;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      }
    }
    /**
     * <code>string product_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getProductIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getProductIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest)) {
        return super.equals(obj);
      }
      com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest other = (com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getProductId()
          .equals(other.getProductId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.joaolucasl.chumlee.DiscountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.joaolucasl.chumlee.DiscountRequest)
        com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest.class, com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest.Builder.class);
      }

      // Construct using com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        productId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountRequest_descriptor;
      }

      @java.lang.Override
      public com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest getDefaultInstanceForType() {
        return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest build() {
        com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest buildPartial() {
        com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest result = new com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest(this);
        result.userId_ = userId_;
        result.productId_ = productId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest) {
          return mergeFrom((com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest other) {
        if (other == com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getProductId().isEmpty()) {
          productId_ = other.productId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productId_ = "";
      /**
       * <code>string product_id = 2;</code>
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string product_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string product_id = 2;</code>
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string product_id = 2;</code>
       */
      public Builder clearProductId() {
        
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>string product_id = 2;</code>
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.joaolucasl.chumlee.DiscountRequest)
    }

    // @@protoc_insertion_point(class_scope:com.github.joaolucasl.chumlee.DiscountRequest)
    private static final com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest();
    }

    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DiscountRequest>
        PARSER = new com.google.protobuf.AbstractParser<DiscountRequest>() {
      @java.lang.Override
      public DiscountRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DiscountRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DiscountRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiscountRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DiscountResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.joaolucasl.chumlee.DiscountResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float discount = 1;</code>
     */
    float getDiscount();

    /**
     * <code>int32 amount = 2;</code>
     */
    int getAmount();
  }
  /**
   * Protobuf type {@code com.github.joaolucasl.chumlee.DiscountResponse}
   */
  public  static final class DiscountResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.joaolucasl.chumlee.DiscountResponse)
      DiscountResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DiscountResponse.newBuilder() to construct.
    private DiscountResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DiscountResponse() {
      discount_ = 0F;
      amount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DiscountResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              discount_ = input.readFloat();
              break;
            }
            case 16: {

              amount_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse.class, com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse.Builder.class);
    }

    public static final int DISCOUNT_FIELD_NUMBER = 1;
    private float discount_;
    /**
     * <code>float discount = 1;</code>
     */
    public float getDiscount() {
      return discount_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private int amount_;
    /**
     * <code>int32 amount = 2;</code>
     */
    public int getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (discount_ != 0F) {
        output.writeFloat(1, discount_);
      }
      if (amount_ != 0) {
        output.writeInt32(2, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (discount_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, discount_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse)) {
        return super.equals(obj);
      }
      com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse other = (com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getDiscount())
          == java.lang.Float.floatToIntBits(
              other.getDiscount()));
      result = result && (getAmount()
          == other.getAmount());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DISCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDiscount());
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.joaolucasl.chumlee.DiscountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.joaolucasl.chumlee.DiscountResponse)
        com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse.class, com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse.Builder.class);
      }

      // Construct using com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        discount_ = 0F;

        amount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.internal_static_com_github_joaolucasl_chumlee_DiscountResponse_descriptor;
      }

      @java.lang.Override
      public com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse getDefaultInstanceForType() {
        return com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse build() {
        com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse buildPartial() {
        com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse result = new com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse(this);
        result.discount_ = discount_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse) {
          return mergeFrom((com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse other) {
        if (other == com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse.getDefaultInstance()) return this;
        if (other.getDiscount() != 0F) {
          setDiscount(other.getDiscount());
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float discount_ ;
      /**
       * <code>float discount = 1;</code>
       */
      public float getDiscount() {
        return discount_;
      }
      /**
       * <code>float discount = 1;</code>
       */
      public Builder setDiscount(float value) {
        
        discount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float discount = 1;</code>
       */
      public Builder clearDiscount() {
        
        discount_ = 0F;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>int32 amount = 2;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>int32 amount = 2;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 amount = 2;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.joaolucasl.chumlee.DiscountResponse)
    }

    // @@protoc_insertion_point(class_scope:com.github.joaolucasl.chumlee.DiscountResponse)
    private static final com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse();
    }

    public static com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DiscountResponse>
        PARSER = new com.google.protobuf.AbstractParser<DiscountResponse>() {
      @java.lang.Override
      public DiscountResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DiscountResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DiscountResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiscountResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.joaolucasl.chumlee.DiscountServiceOuterClass.DiscountResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_joaolucasl_chumlee_DiscountRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_joaolucasl_chumlee_DiscountRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_joaolucasl_chumlee_DiscountResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_joaolucasl_chumlee_DiscountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025DiscountService.proto\022\035com.github.joao" +
      "lucasl.chumlee\"6\n\017DiscountRequest\022\017\n\007use" +
      "r_id\030\001 \001(\t\022\022\n\nproduct_id\030\002 \001(\t\"4\n\020Discou" +
      "ntResponse\022\020\n\010discount\030\001 \001(\002\022\016\n\006amount\030\002" +
      " \001(\0052\203\001\n\017DiscountService\022p\n\013GetDiscount\022" +
      "..com.github.joaolucasl.chumlee.Discount" +
      "Request\032/.com.github.joaolucasl.chumlee." +
      "DiscountResponse\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_joaolucasl_chumlee_DiscountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_joaolucasl_chumlee_DiscountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_joaolucasl_chumlee_DiscountRequest_descriptor,
        new java.lang.String[] { "UserId", "ProductId", });
    internal_static_com_github_joaolucasl_chumlee_DiscountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_joaolucasl_chumlee_DiscountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_joaolucasl_chumlee_DiscountResponse_descriptor,
        new java.lang.String[] { "Discount", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
